export default [
  {
    src: "assets/3dflowfields.png",
    alt: "3D Vector flow fields 002 by Maks Surguy",
    title: "\"3D Vector flow fields 002\"",
    link: "https://www.instagram.com/p/CPaAABSHHII/",
    linkText: "View on Instagram",
  },
  {
    src: "assets/rain.png",
    alt: "Infinite Rain by Maks Surguy",
    title: "\"Infinite Rain\"",
    link: "https://www.instagram.com/p/CMAU4lInB59/",
    linkText: "View on Instagram",
  },
  {
    src: "assets/nft_museum.jpg",
    alt: "Seattle NFT Museum exhibit by Maks Surguy",
    title: "NFT artwork Exhibit at Seattle NFT Museum",
    link: "https://www.instagram.com/p/CceltaIMTtK/",
    linkText: "View on Instagram",
  },
  {
    src: "assets/nft_flowfields.png",
    alt: "Vector Field 005 NFT by Maks Surguy",
    title: "\"Vector Field 005\"",
    link: "https://objkt.com/asset/hicetnunc/1343",
    linkText: "View on OBJKT NFT Marketplace",
  },
  {
    src: "assets/lifeForms.png",
    alt: "Connect to Disconnect NFT by Maks Surguy",
    title: "\"Connect to Disconnect\"",
    link: "https://objkt.com/asset/hicetnunc/254160",
    linkText: "View on OBJKT NFT Marketplace",
  },
  {
    src: "assets/ai_art.jpg",
    alt: "AI art by Maks Surguy",
    title: "Experiments with AI and generative forms",
    link: "https://www.instagram.com/p/CFOAsTYnmAu/",
    linkText: "View on Instagram",
  },
  {
    src: "assets/drawingBots.png",
    alt: "Drawing robot art by Maks Surguy",
    title: "Art made with drawing robots",
    link: "https://www.youtube.com/watch?v=WKcN-lsKqK4",
    linkText: "View on Youtube",
  },
  {
    src: "assets/showreel.png",
    alt: "Drawing robot art by Maks Surguy",
    title: "Generative Art Showreel",
    link: "https://www.youtube.com/watch?v=KYkbtBbBdIk",
    linkText: "View on Youtube",
  },
];